# Generated by Django 3.2.3 on 2021-08-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, null=True)),
                ('adress', models.CharField(blank=True, max_length=127, null=True)),
                ('email', models.EmailField(blank=True, max_length=127, null=True)),
                ('phone', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
    ]
